spring:
  kafka:
    consumer:
      group-id: spring-boot-kafka-group
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

spring-boot-kafka:
  topic-name: spring-boot-kafka-topic
  messages-per-request: 10
